# Generated by Django 3.0.5 on 2020-05-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metcast',
            options={'verbose_name': 'Прогноз погоды', 'verbose_name_plural': 'Прогноз погоды'},
        ),
    ]
